### ISSUE TITLE
Error in SABnzbdConnector

### ISSUE THREAD

**Issue by vitolibrarius** [vitolibrarius/contenta#103]
```
Feb 14, 2016 15:01	**error**	Netconfig/testConnection(3)
libs/connectors/SABnzbdConnector.php(42)

(8) Undefined variable: json
	application/controller/Netconfig.php 179 calling testConnnector()
	application/libs/Application.php 66 calling testConnection()
	vitoLibrarius/contenta/index.php 32 calling __construct()
```

**Comment by vitolibrarius** [comment]
```
Exception expect one parameter #0 /volume1/web/contenta/application/libs/connectors/SABnzbdConnector.php(201): connectors\SABnzbdConnector->performGET('http://localhos...')
#1 /volume1/web/contenta/application/processor/FluxStatusUpdater.php(73): connectors\SABnzbdConnector->delete('SABnzbd_nzo_ITf...')
#2 /volume1/web/contenta/Daemon.php(171): processor\FluxStatusUpdater->processData()
#3 {main}
```

**Comment by vitolibrarius** [comment]
should be using ```mode=history&name=delete```, not ```mode=queue&name=delete```
