### ISSUE TITLE
Gateway timeout error when updating some data

### ISSUE THREAD

**Issue by vitolibrarius** [vitolibrarius/contenta#108]
Daemon -> character_1807
`libs/connectors/EndpointConnector.php	(299)`
`'connectors\ResponseErrorException' with message 'Return code (504): Gateway Time-out ' in libs/connectors/EndpointConnector.php:299`
`Stack trace:`
`#0 libs/connectors/JSON_EndpointConnector.php(53): performGET(string, boolean)`
`#1 libs/connectors/ComicVineConnector.php(474): performGET(string, boolean)`
`#2 libs/connectors/ComicVineConnector.php(120): performGET(string, boolean)`
`#3 libs/connectors/ComicVineConnector.php(141): details(string, string, string, array)`
`#4 application/processor/ComicVineImporter.php(279): characterDetails(string)`
`#5 application/processor/ContentMetadataImporter.php(392): preprocess_character(array)`
`#6 vitoLibrarius/contenta/Daemon.php(171): processData()`

**Comment by vitolibrarius** [comment]
Also Issues
`'connectors\ResponseErrorException' with message 'Return code (504): Gateway Time-out ' in libs/connectors/EndpointConnector.php:299`
`Stack trace:`
`#0 libs/connectors/JSON_EndpointConnector.php(53): performGET(string, boolean)`
`#1 libs/connectors/ComicVineConnector.php(474): performGET(string, boolean)`
`#2 libs/connectors/ComicVineConnector.php(120): performGET(string, boolean)`
`#3 libs/connectors/ComicVineConnector.php(165): details(string, string, string, array)`
`#4 application/processor/ComicVineImporter.php(470): issueDetails(string)`
`#5 application/processor/ContentMetadataImporter.php(392): preprocess_publication(array)`
`#6 application/processor/UploadImport.php(405): processData()`
`#7 web/contenta/Daemon.php(171): processData()`
