### ISSUE TITLE
SABnzbd json response is not always encoded properly

### ISSUE THREAD

**Issue by vitolibrarius** [vitolibrarius/contenta#22]
```
- 'connectors\ResponseErrorException' with message 'JSON_ERROR_CTRL_CHAR' in libs/connectors/JSON_EndpointConnector.php:67
Stack trace:
#0 libs/connectors/SABnzbdConnector.php(264): performGET(string, boolean)
#1 libs/connectors/SABnzbdConnector.php(49): performGET(string)
#2 libs/connectors/SABnzbdConnector.php(149): simpleRequestForMode(string)
#3 libs/connectors/SABnzbdConnector.php(156): history()
#4 application/processor/FluxStatusUpdater.php(64): historySlots()
#5 web/contenta/Daemon.php(158): processData()
```

**Comment by vitolibrarius** [comment]
problem in this case appears to be control characters created as part of the post-processing script in SABnzbd.  The same error exists in the XML response so there is no solution that I can see except submitting a patch to SABnzbd
