### ISSUE TITLE
Import metadata finds error where record is not finalized

### ISSUE THREAD

**Issue by vitolibrarius** [vitolibrarius/contenta#94]
Story Arc Updates	application/processor/ContentMetadataImporter.php line 311
```
'Exception' with message 'All objects should be in finalize state array ( 'name' => 'dupe', 'xurl' => 'http://www.comicvine.com/dupe/4010-4792/', 'xid' => '4792', 'xsource' => 'ComicVine', 'meta_force' => false, 'image' => array ( 'overwrite' => false, ), 'meta_type' => 'publisher', )' in application/processor/ContentMetadataImporter.php:311 
Stack trace: 
#0 application/processor/ComicVineImporter.php(518): finalize(object, array) 
#1 application/processor/ContentMetadataImporter.php(431): finalize_publisher(array) 
#2 web/contenta/Daemon.php(166): processData()
```

**Comment by vitolibrarius** [comment]
may be related 
```
'Exception' with message 'failed to find object for NULL' in application/processor/ComicVineImporter.php:618 Stack trace: #0 application/processor/ContentMetadataImporter.php(431): finalize_story_arc(array) #1 web/contenta/Daemon.php(166): processData()
```
